### ISSUE TITLE
Bug: Almost all debrid links crash

### ISSUE THREAD

**Issue by Terandium** [debridmediamanager/zurg-testing#114]
**Expected Behavior**
All torrents to not crash :)

**Actual Behavior**
Pretty much all torrents have that error (see image)
![image](https://github.com/user-attachments/assets/337e12d4-cf0d-4032-8547-e661ec61e86a)

**Detailed Steps**
Few days ago my real debrid account got suspended, but that has been resolved and after it got reinstated everything worked fine. So I don't think that is relevent, all the files and links are also in my debrid webdav

Yesterday I added info_logging=info to docker compose file, and since then it hasnt worked. I had to restart the docker image multiple times, as I couldnt get it to work at first. 

**Operating System**
Proxmox plex lxc (linux)

**Environment Setup**
```yaml
version: '3.8'

services:
  zurg:
    image: ghcr.io/debridmediamanager/zurg-testing:latest
    restart: unless-stopped
    ports:
      - 9999:9999
    environment:
      LOG_LEVEL: "INFO" #remove for debug logging
    volumes:
      - ./plex_update.sh:/app/plex_update.sh
      - ./config.yml:/app/config.yml
      - zurgdata:/app/data

  rclone:
    image: rclone/rclone:latest
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      PUID: 1000
      PGID: 1000
    volumes:
      - /mnt/zurg:/data:rshared # CHANGE /mnt/zurg WITH YOUR PREFERRED MOUNT PATH
      - ./rclone.conf:/config/rclone/rclone.conf
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    depends_on:
      - zurg
    command: "mount zurg: /data --allow-other --allow-non-empty --dir-cache-time 10s --vfs-cache-mode off"

volumes:
  zurgdata:
```

**Logs**
![image](https://github.com/user-attachments/assets/5102eadf-fdfb-4d5b-8b60-02450524f112)
All the logs are normal except that, which gets repeated for every torrent.

**Rclone Configuration**
```yaml
[zurg]
type = webdav
url = http://zurg:9999/dav
vendor = other
pacer_min_sleep = 0

[zurghttp]
type = http
url = http://zurg:9999/http
no_head = false
no_slash = false
```

**Zurg Configuration**
```yaml
zurg: v1
token:<redacted>
check_for_changes_every_secs: 30
enable_repair: true
auto_delete_rar_torrents: false
rate_limit_sleep_secs: 6
retries_until_failed: 5
serve_from_rclone: false
verify_download_link: false
use_download_cache: true
on_library_update: sh plex_update.sh "$@"
```

removed directories part, as it isn't relevant

**Screenshots**
![image](https://github.com/user-attachments/assets/337e12d4-cf0d-4032-8547-e661ec61e86a)
