### ISSUE TITLE
Bug: Incorrect mount after server reboot

### ISSUE THREAD

**Issue by gianlucalauro** [debridmediamanager/zurg-testing#118]
**Actual Behavior**
When i restart my compose or the entire machine, In Plex container, i don't see my media mounted (also in rdtclient, radarr, etc). If i restart all of these (except zurg or rclone) they show me correctly all the files

**Operating System**
Fedora 40 - Docker 27.1.2

**Environment Setup**
Compose:
```yml
services:
  zurg:
      container_name: zurg
      image: ghcr.io/debridmediamanager/zurg-testing:latest
      restart: unless-stopped
      networks:
        - "home"
      ports:
        - 9999:9999
      volumes:
        - /home/gianluca/zurg-testing/plex_update.sh:/app/plex_update.sh
        - /home/gianluca/zurg-testing/config.yml:/app/config.yml
        - zurgdata:/app/data
  
    rclone:
      container_name: rclone
      image: rclone/rclone:latest
      restart: unless-stopped
      networks:
        - "home"
      environment:
        TZ: Europe/Rome
        PUID: 0
        PGID: 0
      volumes:
        - /mnt/zurg:/data:rshared
        - /home/gianluca/zurg-testing/rclone.conf:/config/rclone/rclone.conf
      cap_add:
        - SYS_ADMIN
      security_opt:
        - apparmor:unconfined
      devices:
        - /dev/fuse:/dev/fuse:rwm
      depends_on:
        - zurg
      command: "mount zurg: /data --allow-other --allow-non-empty --dir-cache-time 10s --vfs-cache-mode full"
  
    rdtclient:
      container_name: rdtclient
      environment:
        PUID: 0
        PGID: 0
      depends_on:
        rclone:
          condition: service_started
        zurg:
          condition: service_healthy
      volumes:
        - /home/gianluca/utils/rdtclient/downloads:/downloads
        - /mnt/zurg:/mnt/zurg
        - /home/gianluca/utils/rdtclient/db:/data/db
      networks:
        - "home"
      ports:
        - 6500:6500
      restart: always
      image: rogerfar/rdtclient
  plex:
      container_name: plex
      ports:
        - "32400:32400"
      networks:
        - "home"
      environment:
        - PUID=0
        - PGID=0
        - VERSION=docker
        - "PLEX_CLAIM=aaa"
      depends_on:
        rclone:
          condition: service_started
        zurg:
          condition: service_healthy
      volumes:
        - "/home/gianluca/utils/plex:/config"
        - "/mnt/mediacenter/Media:/Media"
        - "/mnt/external_hdd/Media:/Media2"
        - "/mnt/debrid:/debrid"
        - "/mnt/zurg/__all__:/mnt/zurg/__all__"
        - "/mnt/external_hdd/nextcloud/Gianluca/files/Fotocamera/Elaborate:/Foto"
      devices:
        - "/dev/dri:/dev/dri"
      restart: unless-stopped
      image: "lscr.io/linuxserver/plex:latest"
```

**Plex Container**
In the container (connecting to bash shell) i see with `$ ls /mnt/zurg` that the folder is empty. When i restart Plex, i see all the contents
