### ISSUE TITLE
Bug: No directories in folder

### ISSUE THREAD

**Issue by SnarkySarky** [debridmediamanager/zurg-testing#122]
**Expected Behavior**
Zurg filters movies and tvshows into seperate folders and an --ALL-- folder 

**Actual Behavior**
the torrents folder just has all data no filtering

**Detailed Steps**
I followed all steps detailed in "how to run zurg in 5 steps"

**Operating System**
MacOS

**Environment Setup**
docker 

**Logs**
https://0x0.st/X3Ze.log

If you are running it in Docker, your container logs will also help.

**Rclone Configuration**
[zurg]
type = webdav
url = http://localhost:9999/dav
vendor = other
pacer_min_sleep = 0

[zurghttp]
type = http
url = http://localhost:9999/http
no_head = false
no_slash = false

**Zurg Configuration**
```
zurg: v1
token: $$$$$$$$$$$$$$
# host: "[::]"
# port: 9999
# username:$$$$$
# password:$$$$$$$$$$
# proxy:
# concurrent_workers: 20
check_for_changes_every_secs: 10
# repair_every_mins: 60
# ignore_renames: false
# retain_rd_torrent_name: false
# retain_folder_name_extension: false
enable_repair: true
auto_delete_rar_torrents: true
# api_timeout_secs: 15
# download_timeout_secs: 10
# enable_download_mount: false
# rate_limit_sleep_secs: 6
# retries_until_failed: 2
# network_buffer_size: 4194304 # 4MB
# serve_from_rclone: false
# verify_download_link: false
# force_ipv6: false
on_library_update: sh plex_update.sh "$@"
#for windows comment the line above and uncomment the line below:
#on_library_update: '& powershell -ExecutionPolicy Bypass -File .\plex_update.ps1 --% "$args"'

directories:
  anime:
    group_order: 10
    group: media
    filters:
      - regex: /\b[a-fA-F0-9]{8}\b/
      - any_file_inside_regex: /\b[a-fA-F0-9]{8}\b/

  shows:
    group_order: 20
    group: media
    filters:
      - has_episodes: true

  movies:
    group_order: 30
    group: media
    only_show_the_biggest_file: true
    filters:
      - regex: /.*/
```

**Screenshots**
[docker-compose.txt](https://github.com/user-attachments/files/17015503/docker-compose.txt)
