### ISSUE TITLE
Bug: Healthcheck fails when username and password are set

### ISSUE THREAD

**Issue by anewlime** [debridmediamanager/zurg-testing#126]
**Expected Behavior**
Healthcheck should account for username and password if set.

**Actual Behavior**
Healthcheck fails when username and password are set.

**Detailed Steps**
1. Set username and password in config.
2. Start container.

**Operating System**
Debian

**Environment Setup**
Docker

`docker-compose.yml`
```
services:
  zurg:
    container_name: zurg
    image: ghcr.io/debridmediamanager/zurg-testing:latest
    ports:
      - 9999:9999
    volumes:
      - ./zurg/config.yml:/app/config.yml
      - ./zurg/data:/app/data
    restart: unless-stopped
```

**Logs**
Not included.

**Rclone Configuration**
```
[zurg]
type = webdav
url = http://zurg:9999/dav
vendor = other
pacer_min_sleep = 0
```

**Zurg Configuration**
`config.yml`
```
zurg: v1
token: redacted
username: redacted
password: redacted
check_for_changes_every_secs: 10
retain_rd_torrent_name: true
retain_folder_name_extension: true
enable_repair: true
directories:
  all:
    filters:
      - regex: /.*/
```

**Screenshots**
Not included.
