### ISSUE TITLE
Request: Combine rclone & zurg?

### ISSUE THREAD

**Issue by Reasonable-Grape2698** [debridmediamanager/zurg-testing#129]
```
FROM ghcr.io/debridmediamanager/zurg-testing:latest

RUN curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip && \
unzip *.zip && cp rclone-*-linux-amd64/rclone /usr/bin && chown root:root /usr/bin/rclone && chmod 755 /usr/bin/rclone

RUN apk add screen fuse3

COPY rclone.conf /root/.config/rclone/rclone.conf

ENTRYPOINT ["sh", "-c", "screen -d -m /app/zurg && rclone mount zurg: /data --allow-other --allow-non-empty --dir-cache-time 10s --vfs-cache-mode full"]
```

Tested and it works as intended. Only downside is you can't customise the rclone command, but I assume this could be done another way to fix that

Docker compose becomes:
```
services:
  zurg:
    image: test:test
    container_name: zurg
    restart: unless-stopped
    volumes:
      - ./scripts/plex_update.sh:/app/plex_update.sh
      - ./config.yml:/app/config.yml
      - zurgdata:/app/data
      - /mnt/zurg:/data:rshared
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    environment:
      TZ: Europe/Berlin
      PUID: 1000
      PGID: 1000

volumes:
  zurgdata:
```
