### ISSUE TITLE
Failed to mount: directory already mounted

### ISSUE THREAD

**Issue by kevoh1516** [debridmediamanager/zurg-testing#40]
Double checked that the directory is not mounted and is empty but it keeps giving me directory already mounted error. It only works when I use `--allow-non-empty`.

Docker version 24.0.7

```
zurg-1    | Logging to logs/zurg-2024-01-21.log
rclone-1  | 2024/01/21 06:22:04 Fatal error: failed to mount FUSE fs: directory already mounted, use --allow-non-empty to mount anyway: /data
zurg-1    | 2024-01-21T05:22:04.611Z	INFO	zurg	Your account will expire in 89 days
zurg-1    | 2024-01-21T05:22:04.768Z	INFO	manager	Compiled into 329 downloads
zurg-1    | 2024-01-21T05:22:04.895Z	INFO	manager	Compiled into 28 torrents, 0 were missing info
rclone-1 exited with code 0
rclone-1  | 2024/01/21 06:22:04 Fatal error: failed to mount FUSE fs: directory already mounted, use --allow-non-empty to mount anyway: /data
rclone-1 exited with code 1
zurg-1    | 2024-01-21T05:22:05.155Z	INFO	manager	Finished initializing torrent manager
zurg-1    | 2024-01-21T05:22:05.156Z	INFO	manager	Checking for broken torrents
zurg-1    | 2024-01-21T05:22:05.156Z	INFO	zurg	Starting server on [::]:9999
zurg-1    | 2024-01-21T05:22:05.156Z	INFO	manager	Starting periodic refresh
rclone-1  | 2024/01/21 06:22:05 Fatal error: failed to mount FUSE fs: directory already mounted, use --allow-non-empty to mount anyway: /data
rclone-1 exited with code 1
rclone-1  | 2024/01/21 06:22:06 Fatal error: failed to mount FUSE fs: directory already mounted, use --allow-non-empty to mount anyway: /data
zurg-1    | 2024-01-21T05:22:06.321Z	INFO	manager	Finished checking for broken torrents
rclone-1 exited with code 1
rclone-1  | 2024/01/21 06:22:07 Fatal error: failed to mount FUSE fs: directory already mounted, use --allow-non-empty to mount anyway: /data
rclone-1 exited with code 1
rclone-1  | 2024/01/21 06:22:09 Fatal error: failed to mount FUSE fs: directory already mounted, use --allow-non-empty to mount anyway: /data
```

```
version: '3.8'

services:
  zurg:
    image: ghcr.io/debridmediamanager/zurg-testing:latest
    restart: unless-stopped
    ports:
      - 9999:9999
    volumes:
      - ./plex_update.sh:/app/plex_update.sh
      - ./config.yml:/app/config.yml
      - zurgdata:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rclone:
    image: rclone/rclone:latest
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      PUID: 1000
      PGID: 1000
    volumes:
      - /mnt/zurg:/data:rshared
      - ./rclone.conf:/config/rclone/rclone.conf
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    depends_on:
      - zurg
    command: "mount zurg: /data --allow-other --dir-cache-time 10s --vfs-cache-mode full"

volumes:
  zurgdata:
```
