### ISSUE TITLE
Unable to use on Mac: Change mount path

### ISSUE THREAD

**Issue by JurajNyiri** [debridmediamanager/zurg-testing#6]
I am using Mac Mini M1 to run this.

When I run `sudo mkdir -p /mnt/zurg` I get:

```
Password:
mkdir: /mnt: Read-only file system
```

I changed the docker-compose like so:

```
version: '3.8'

services:
  zurg:
    image: ghcr.io/debridmediamanager/zurg-testing:latest
    restart: unless-stopped
    ports:
      - 9999:9999
    volumes:
      - ./config.yml:/app/config.yml
      - zurgdata:/app/data

  rclone:
    image: rclone/rclone:latest
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      PUID: 1000
      PGID: 1000
    volumes:
      - /Users/jurajnyiri/media/zurg:/data:rshared
      - ./rclone.conf:/config/rclone/rclone.conf
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    depends_on:
      - zurg
    command: "mount zurg: /data --allow-non-empty --allow-other --uid=1000 --gid=1000 --dir-cache-time 10s --read-only"

volumes:
  zurgdata:
```

Then I ran `docker compose up -d`.

Via `docker ps` I see 2 containers running:

`rclone/rclone:latest` and `ghcr.io/debridmediamanager/zurg-testing:latest`

Docker logs for zurg shows:

```
2023-11-11T10:38:10.396Z	DEBUG	config	Loading config file ./config.yml
2023-11-11T10:38:10.399Z	DEBUG	config	Detected config version: v1
2023-11-11T10:38:14.144Z	INFO	manager	Got 1980 torrents
2023-11-11T10:38:14.446Z	INFO	manager	Starting periodic refresh
2023-11-11T10:38:14.446Z	INFO	zurg	Starting server on [::]:9999
```

Docker logs for rclone shows nothing.

The issue is, directory /Users/jurajnyiri/media/zurg is empty.

```
jurajnyiri@Jurajs-Mac-mini zurg-testing % chmod -R 777 /Users/jurajnyiri/media/zurg
jurajnyiri@Jurajs-Mac-mini zurg-testing % ls -la /Users/jurajnyiri/media/zurg      
total 0
drwxrwxrwx  2 jurajnyiri  staff   64 Nov 11 11:31 .
```

What am I doing wrong? Could you please guide me on how to debug this further?
