### ISSUE TITLE
Bug: ERROR : IO error: couldn't list files: Not Implemented Method: NotImplemented: 501 Not Implemented

### ISSUE THREAD

**Issue by subexx** [debridmediamanager/zurg-testing#89]
Getting this error in rclone frequently and has to reboot the container to make it work again.

**Detailed Steps**
Using Zurg with radarr, sonarr and rdtclient. It works most of the time. But has to keep an eye on it frequesntly because of this error.

**Operating System**
Running Zurg in Docker in Ubuntu 22.04 arm64.

**Environment Setup**

services:

```
  zurg:
    image: "ghcr.io/debridmediamanager/zurg-testing:v0.9.3-hotfix.11"
    container_name: "zurg"
    restart: "unless-stopped"
    ports:
      - "9999:9999"
    volumes:
      - "/home/docker/zurg/config.yml:/app/config.yml"
      - "zurgdata:/app/data"
  rclone:
    image: "rclone/rclone:latest"
    container_name: "rclone"
    restart: "unless-stopped"
    environment:
      TZ: "Australia/Melbourne"
      PUID: "1001"
      PGID: "1001"
    volumes:
      - "/mnt/remote/realdebrid:/data:rshared"
      - "/home/docker/zurg/rclone.conf:/config/rclone/rclone.conf"
      - "/mnt:/mnt"
    cap_add:
      - "SYS_ADMIN"
    security_opt:
      - "apparmor:unconfined"
    devices:
      - "/dev/fuse:/dev/fuse:rwm"
    depends_on:
      - "zurg"
    command: "mount zurg: /data --allow-non-empty --allow-other --dir-cache-time 10s --vfs-cache-mode full"

volumes:
  zurgdata:
```

**Logs**
      
2024/02/18 20:23:12 ERROR : IO error: couldn't list files: Not Implemented Method: NotImplemented: 501 Not Implemented
2024/02/18 20:23:14 ERROR : IO error: couldn't list files: Not Implemented Method: NotImplemented: 501 Not Implemented
2024/02/18 20:23:15 ERROR : IO error: couldn't list files: Not Implemented Method: NotImplemented: 501 Not Implemented
2024/02/18 20:23:16 ERROR : IO error: couldn't list files: Not Implemented Method: NotImplemented: 501 Not Implemented
2024/02/18 23:23:13 ERROR : IO error: couldn't list files: Not Implemented Method: NotImplemented: 501 Not Implemented
2024/02/18 23:23:15 ERROR : IO error: couldn't list files: Not Implemented Method: NotImplemented: 501 Not Implemented

If you are running it in Docker, your container logs will also help.

**Rclone Configuration**
```
[zurg]
type = webdav
url = http://zurg:9999/dav
vendor = other
pacer_min_sleep = 0

[zurghttp]
type = http
url = http://zurg:9999/http
no_head = false
no_slash = false

```

**Zurg Configuration**
```
# Zurg configuration version
zurg: v1
token: 4LMUCTXXXXXXXXXXXXXXX # https://real-debrid.com/apitoken

host: "[::]"
port: 9999
concurrent_workers: 32
check_for_changes_every_secs: 15
ignore_renames: true
retain_rd_torrent_name: false
retain_folder_name_extension: false
auto_delete_rar_torrents: true
enable_repair: true
on_library_update: |
  for arg in "$@"
  do
      echo "detected update on: $arg"
  done
network_buffer_size: 1048576
serve_from_rclone: false
verify_download_link: false
force_ipv6: false
rate_limit_sleep_secs: 6
retries_until_failed: 5
repair_every_mins: 60
api_timeout_secs: 4
download_timeout_sec: 2

directories:
  torrents:
    group: 1
    filters:
      - regex: /.*/

```
