### ISSUE TITLE
Bug: Files cannot be read or dowloaded

### ISSUE THREAD

**Issue by sponde25** [debridmediamanager/zurg-testing#98]
**Expected Behavior**
Jellyfin library should load and play files. The <server>:9999/http should let me download the files.
**Actual Behavior**
The http server throws error File is unavailable.
Jellyfin UI shows all the media but cannot run anything. I get this error in Jellyfin:

> [ERR] Error in "ffprobe"
> MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.

**Detailed Steps**
Running Zurg in the docker

**Operating System**
Ubuntu 20.03

**Environment Setup**
```
version: '3.8'

services:
  zurg:
    image: ghcr.io/debridmediamanager/zurg-testing:latest
    restart: unless-stopped
    ports:
      - 9999:9999
    volumes:
      - ./config.yml:/app/config.yml
      - zurgdata:/app/data

  rclone:
    image: rclone/rclone:latest
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      PUID: 1000
      PGID: 1000
    volumes:
      - /mnt/zurg:/data:rshared # CHANGE /mnt/zurg WITH YOUR PREFERRED MOUNT PATH
      - ./rclone.conf:/config/rclone/rclone.conf
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    depends_on:
      - zurg
    command: "mount zurg: /data --allow-other --allow-non-empty --dir-cache-time 10s --vfs-cache-mode full"

volumes:
  zurgdata:
```

**Logs**
https://0x0.st/Hhph.log

**Zurg Configuration**
```
zurg: v1
token: 
# host: "[::]"
# port: 9999
# username:
# password:
# proxy:
# concurrent_workers: 20
check_for_changes_every_secs: 10
# repair_every_mins: 60
# ignore_renames: false
# retain_rd_torrent_name: false
# retain_folder_name_extension: false
enable_repair: true
auto_delete_rar_torrents: true
enable_download_mount: true
# api_timeout_secs: 15
# download_timeout_secs: 10
# enable_download_mount: false
# rate_limit_sleep_secs: 6
# retries_until_failed: 2
# network_buffer_size: 4194304 # 4MB
# serve_from_rclone: false
# verify_download_link: false
# force_ipv6: false
# on_library_update: sh plex_update.sh "$@"
#for windows comment the line above and uncomment the line below:
#on_library_update: '& powershell -ExecutionPolicy Bypass -File .\plex_update.ps1 --% "$args"'

directories:
  anime:
    group_order: 10
    group: media
    filters:
      - regex: /\b[a-fA-F0-9]{8}\b/
      - any_file_inside_regex: /\b[a-fA-F0-9]{8}\b/

  shows:
    group_order: 20
    group: media
    filters:
      - has_episodes: true

  movies:
    group_order: 30
    group: media
    only_show_the_biggest_file: true
    filters:
      - regex: /.*/
  ```
